### ISSUE TITLE
evcxr jupyter notebook

### ISSUE THREAD

**Issue by wangjiawen2013** [alceal/plotlars#10]
Hi,
Does plotlars support evexr jupyter notebook ? Maybe you can assign the html to a variable and then print the variable in jupyter notebook. Now plotly.rs supports evcxr jupyter notebook already.
`println!("EVCXR_BEGIN_CONTENT text/html\n{}\nEVCXR_END_CONTENT", html)`
https://github.com/evcxr/evcxr/blob/main/evcxr_jupyter/README.md

**Comment by alceal** [comment]
Plotlars works with Jupyter notebook. The method `plot` recognizes if you are using it or not.

**Comment by alceal** [comment]
<img width="1032" alt="Screenshot 2024-09-03 at 08 14 11" src="https://github.com/user-attachments/assets/167a7bab-5f3b-41ed-8b22-73b644f94a86">
