### ISSUE TITLE
Add example of plotting two lines on the same graph

### ISSUE THREAD

**Issue by paulirotta** [alceal/plotlars#19]
It is not clear- is this currently possible?

**Comment by alceal** [comment]
Hi @paulirotta ,

Do you mean something like this?


![](https://imgur.com/PaXG300.png)

**Comment by paulirotta** [comment]
Very nice! Much to like on your lib

It's great to have such in /examples for quick start answering various new user questions. If you go that way, I'll see if I have any to offer as time permits

**Comment by paulirotta** [comment]
Probably my lazy bad for missing this in the docs... 😋

**Comment by alceal** [comment]
Each kind of plot has an example in its documentation page. Furthermore, the repository has a data folder which contains data files that I use for the examples.
