### ISSUE TITLE
plotlars 0.5.0 crates.io version doesn't have up-to-date dependencies

### ISSUE THREAD

**Issue by rcornea** [alceal/plotlars#20]
using the example in the README fails because cargo adds version tag 0.5.0 of plotlars, which does not include commit https://github.com/alceal/plotlars/commit/b19f73648d902ad735a116a1c77a2f9a6a9223f2

the `dataset` variable DataFrame type doesn't match between plotlars 0.5.0 and polars 0.43.1 so new users are facing an error straight out of the box.

perhaps it would be wise to release a small version update for crates.io that includes the above commit's significant dependency change?

if not, people should be directed in the README.md to either add the `main` branch of this repo in their cargo.toml files to get a working configuration, or to lock the polars crate to the older 0.42.0 version.

**Comment by alceal** [comment]
Thank you! I’ll create a new small version to update the dependencies.
